# -*- coding: utf-8 -*-
"""TOPIX500銘柄.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_R078_1WeAqM6vC9HRVTkuIL_rntFS39
"""

#東京証券取引所から銘柄一覧データを取得する
#https://www.jpx.co.jp/markets/statistics-equities/misc/01.html

import pandas as pd

tse_list = pd.read_excel('data_j.xls', header=0)

tse_list

tse1 = tse_list[tse_list['市場・商品区分'] == '市場第一部（内国株）']
tse1

# TOPIX500の銘柄を抽出する

# '市場・商品区分'列のデータが”市場第一部（内国株）”だけの行を選択する
tse1 = tse_list[tse_list['市場・商品区分'] == '市場第一部（内国株）']

# ”規模区分”列が"core30 Large70 Mid400”の行だけを選択する
topix500 = tse1[(tse1['規模区分'] == 'TOPIX Core30') | #パイプライン
                (tse1['規模区分'] == 'TOPIX Large70') |
                (tse1['規模区分'] == 'TOPIX Mid400')]

topix500

# 33業種コード,33業種区分ごとの銘柄数を算出
#特定の値がいくつあるか数えるとき、groupby() してから size()
category_count = topix500.groupby(['33業種コード','33業種区分']).size()
print(category_count)

# 33業種コード,33業種区分を抽出
#グループ化して辞書型で表示する。
industry_category = topix500.groupby(['33業種コード','33業種区分']).groups.keys()
print(industry_category)

import datetime
from datetime import date,timedelta

!pip install pandas-datareader
import pandas_datareader.data as web

# 2020/11/2〜2021/2/5の株価を取得する
base_date = datetime.datetime(2020, 1, 26)
end_date=datetime.datetime(2021, 2, 5)

# 業種単位の株価上昇率格納用のDataFrameを用意する
category_df = None

# 業種ごとに変動率を計算する
for category in industry_category:
    
    category_code = category[0]     # 33業種コード
    category_class = category[1]    # 33業種区分
    
    # 指定した業種の銘柄を抽出
    brands = topix500[topix500['33業種区分'] == category_class]
    
    # 銘柄コードの末尾に.JPを付加する
    symbols = []
    for code in brands['コード']:
        symbols.append('{0:d}.JP'.format(code))

    # 指定銘柄コードの株価を取得する
    stock_price = web.DataReader(symbols, 'stooq', start=base_date, end=end_date)
    print(stock_price)

"""# 各銘柄の上昇率を計算"""

# 銘柄ごとに上昇率を計算し、ディショクナリに格納する
dict = {}
for symbol in symbols:
    
    # 基準日付からの上昇率を計算する
    base_date_str = base_date.strftime('%04Y-%02m-%02d')
    base_price = stock_price.loc[base_date_str][('Close',symbol)]
    increase_rate = stock_price[('Close',symbol)] / base_price.iloc[0]
    
    # ディクショナリに格納する
    dict[symbol] = increase_rate
    
# ディクショナリからDataFrame作成
df = pd.DataFrame(dict)

# 銘柄ごとに上昇率を計算し、ディショクナリに格納する
dict = {}
for symbol in symbols:
    
    # 基準日付からの上昇率を計算する
    base_date_str = base_date.strftime('%04Y-%02m-%02d')
    base_price = stock_price.loc[base_date_str][('Close',symbol)]
    increase_rate = stock_price[('Close',symbol)] / base_price.iloc[0]
    
    # ディクショナリに格納する
    dict[symbol] = increase_rate
    
# ディクショナリからDataFrame作成
df = pd.DataFrame(dict)

